; =============================
; General PHP settings
; =============================
display_errors=On
memory_limit=512M
upload_max_filesize=50M
post_max_size=50M
date.timezone=Asia/Ho_Chi_Minh

; =============================
; Sessions stored in Redis
; =============================
; Sử dụng Redis làm session handler
session.save_handler = redis

; Dùng host của service docker-compose (web-redis)
; không dùng 127.0.0.1 vì trong container nó không phải localhost
session.save_path = "tcp://web-redis:6379"

; (tuỳ chọn) prefix để dễ nhận biết trên redis-cli
; session.prefix = "PHPREDIS_SESSION:"

; (tuỳ chọn) thời gian sống session (giây)
session.gc_maxlifetime = 3600

session.name = KEY
